name: Build and Release Tauri App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-22.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: cargo

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libssl-dev \
            libgtk-3-dev \
            squashfs-tools \
            build-essential \
            curl \
            wget \
            file \
            pkg-config \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Verify Tauri project structure
        run: ls -R && ls -R src-tauri

      - name: Build Tauri App with debug info
        env:
          RUST_BACKTRACE: full
        run: |
          echo "Building Tauri app with verbose output..."
          tauri build --verbose
        working-directory: ./

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/
